# Generated by Django 6.0.5 on 2026-05-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_category_touristsite_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristsite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
