# Generated by Django 6.0.5 on 2026-05-31 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_touristsite_latitude_touristsite_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('creatrd_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism.touristsite')),
            ],
        ),
    ]
