# Generated by Django 6.0.5 on 2026-05-31 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='creatrd_at',
            new_name='created_at',
        ),
    ]
