# Generated by Django 6.0.6 on 2026-06-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_rename_authors_review_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='authors',
            field=models.CharField(default='anonyme', max_length=100),
            preserve_default=False,
        ),
    ]
